micronaut:
  application:
    name: server
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:classpath:certs/private.pem}"'
              jws-algorithm: HS256
rsa:
  rsa-private-key: classpath:certs/private.pem
  rsa-public-key: classpath:certs/public.pem
  rsa-key-pair: classpath:certs/rsa-2048bit-key-pair.pem

max-http-request-header-size: 20KB

datasource:
  dialect: postgres
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/pediamed?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  username: postgres
  password: postgres
sql:
  init:
    mode: always
jpa:
  default:
    packages-to-scan:
      - 'server'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true